### Listar todos os pacientes
GET http://localhost:3000/pacientes/listarpaciente

### Criar novo paciente
POST http://localhost:3000/pacientes/criarpaciente
Content-Type: application/json

{
  "nome": "Lucas Teste",
  "datanascimento": "2002-09-19",
  "email": "lucas@email.com",
  "cpf": "12345678900",
  "endereco": "Rua XPTO, 456",
  "criadoPor": "Admin"
}

### Atualizar um paciente existente
PUT http://localhost:3000/pacientes/atualizarpaciente/1
Content-Type: application/json

{
  "nome": "Lucas Teste Atualizado",
  "datanascimento": "2002-09-19",
  "email": "lucas.updated@email.com",
  "cpf": "12345678900",
  "endereco": "Rua XPTO, 456 Atualizada",
  "criadoPor": "Admin"
}

### Deletar um paciente
DELETE http://localhost:3000/pacientes/deletarpaciente/2